version: '3.5'

services:
  pqldb:
    image: postgres
    ports:
      - "5001:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    volumes:
      - users-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8001:8080"
volumes:
  users-data:
