version: '3.5'

services:
  pqldb:
    image: postgres
    ports:
      - "5000:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vehicle_db
    volumes:
      - vehicle-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"
volumes:
  vehicle-data:
