version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: my_admin
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: keycloak_db
    ports:
      - "5432:5432"
    volumes:
      - keycloak_db:/var/lib/postgresql/data
  kc:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_ADDR: db
      DB_VENDOR: POSTGRES
      DB_DATABASE: keycloak_db
      DB_SCHEMA: public
      DB_USER: my_admin
      DB_PASSWORD: my_password
#      KEYCLOAK_HOSTNAME: keycloakservice
      KEYCLOAK_USER: kc_admin
      KEYCLOAK_PASSWORD: kc_password
    ports:
      - "8080:8080"
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - "8011:8080"
volumes:
  keycloak_db:
