version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: my_admin
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: keycloak_db
    ports:
      - "5432:5432"
    volumes:
      - keycloak_db:/var/lib/postgresql/data
  kc:
    image: jboss/keycloak:latest
    environment:
      DB_ADDR: db
      DB_VENDOR: POSTGRES
      DB_DATABASE: keycloak_db
      DB_SCHEMA: public
      DB_USER: my_admin
      DB_PASSWORD: my_password
#      KEYCLOAK_HOSTNAME: keycloak
      KEYCLOAK_USER: kc_admin
      KEYCLOAK_PASSWORD: kc_password
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./keywind:/opt/jboss/keycloak/themes/keywind
    command:
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      - "-Dkeycloak.theme.import=/opt/jboss/keycloak/themes/keywind"
      - "-Djboss.modules.system.pkgs=org.jboss.byteman"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8011:8080"
volumes:
  keycloak_db:
